/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { IDL } from '@icp-sdk/core/candid';

export const RequestId = IDL.Nat;
export const Time = IDL.Int;
export const TaskStatus = IDL.Variant({
  'assignedAsPartner' : IDL.Record({
    'effectiveHours' : IDL.Nat,
    'partnerId' : IDL.Principal,
    'workDeadline' : IDL.Opt(Time),
    'workBriefing' : IDL.Text,
  }),
  'rejectedByPartner' : IDL.Record({ 'revisionByPartner' : IDL.Text }),
  'revisionRequestedByAsistenmu' : IDL.Record({
    'revisionByAsistenmu' : IDL.Text,
    'partnerId' : IDL.Principal,
  }),
  'newlyCreated' : IDL.Null,
  'qaRequestedByPartner' : IDL.Record({ 'partnerId' : IDL.Principal }),
  'offerSentToPartner' : IDL.Record({
    'effectiveHours' : IDL.Nat,
    'partnerId' : IDL.Principal,
    'workBriefing' : IDL.Text,
  }),
  'completedBYPartnerAndAsistenmu' : IDL.Record({
    'finalReport' : IDL.Text,
    'partnerId' : IDL.Principal,
  }),
  'inProgressByPartner' : IDL.Record({ 'partnerId' : IDL.Principal }),
});
export const TaskRecordStatus = IDL.Variant({
  'active' : IDL.Null,
  'completed' : IDL.Null,
  'qaRequested' : IDL.Null,
  'rejected' : IDL.Null,
  'revisionRequested' : IDL.Null,
});
export const Request = IDL.Record({
  'id' : RequestId,
  'status' : TaskStatus,
  'client' : IDL.Principal,
  'title' : IDL.Text,
  'createdAt' : Time,
  'revisionCount' : IDL.Nat,
  'deadline' : IDL.Opt(Time),
  'updatedAt' : Time,
  'details' : IDL.Text,
  'asistenmu' : IDL.Principal,
  'recordStatus' : TaskRecordStatus,
});
export const UserRole__1 = IDL.Variant({
  'admin' : IDL.Null,
  'user' : IDL.Null,
  'guest' : IDL.Null,
});
export const RequestInput = IDL.Record({
  'title' : IDL.Text,
  'deadline' : IDL.Opt(Time),
  'subscriptionId' : IDL.Nat,
  'details' : IDL.Text,
});
export const BaseServiceType = IDL.Variant({
  'fokus' : IDL.Null,
  'jaga' : IDL.Null,
  'rapi' : IDL.Null,
  'tenang' : IDL.Null,
});
export const ServiceStatus = IDL.Variant({
  'active' : IDL.Null,
  'hold' : IDL.Null,
  'suspended' : IDL.Null,
});
export const SubscriptionRecord = IDL.Record({
  'id' : IDL.Nat,
  'status' : ServiceStatus,
  'client' : IDL.Principal,
  'serviceType' : BaseServiceType,
  'endDate' : Time,
  'pricePerService' : IDL.Nat,
  'quantity' : IDL.Nat,
  'asistenmu' : IDL.Opt(IDL.Principal),
  'sharedPrincipals' : IDL.Vec(IDL.Principal),
  'startDate' : Time,
});
export const UserProfile = IDL.Record({
  'name' : IDL.Text,
  'whatsapp' : IDL.Text,
  'email' : IDL.Text,
  'company' : IDL.Opt(IDL.Text),
});
export const ServiceFilter = IDL.Record({
  'status' : IDL.Opt(ServiceStatus),
  'serviceType' : IDL.Opt(BaseServiceType),
  'endDate' : IDL.Opt(Time),
  'minQuantity' : IDL.Opt(IDL.Nat),
  'startDate' : IDL.Opt(Time),
});
export const ServicePage = IDL.Record({
  'subscriptions' : IDL.Vec(SubscriptionRecord),
  'total' : IDL.Nat,
  'page' : IDL.Nat,
  'pageSize' : IDL.Nat,
});
export const PartnerProfile = IDL.Record({
  'completedTasks' : IDL.Nat,
  'hourlyRate' : IDL.Nat,
  'pendingEarnings' : IDL.Nat,
  'companyName' : IDL.Text,
  'rejectedTasks' : IDL.Nat,
  'pendingTasks' : IDL.Nat,
  'skills' : IDL.Vec(IDL.Text),
});
export const SubscriptionSummary = IDL.Record({
  'totalSubscriptions' : IDL.Nat,
  'activeSubscriptions' : IDL.Nat,
  'hasActiveAsistenmu' : IDL.Bool,
});
export const PartnerStatus = IDL.Variant({
  'active' : IDL.Null,
  'pending' : IDL.Null,
});
export const UserRole = IDL.Variant({
  'client' : IDL.Null,
  'admin' : IDL.Null,
  'asistenmu' : IDL.Null,
  'partner' : PartnerStatus,
});
export const UserIdentity = IDL.Record({
  'principal' : IDL.Principal,
  'name' : IDL.Text,
  'role' : UserRole,
});
export const PartnerSearchCriteria = IDL.Record({
  'maxHourlyRate' : IDL.Opt(IDL.Nat),
  'minHourlyRate' : IDL.Opt(IDL.Nat),
  'companyName' : IDL.Opt(IDL.Text),
  'skills' : IDL.Opt(IDL.Text),
});
export const PartnerSearchResult = IDL.Record({
  'completedTasks' : IDL.Nat,
  'hourlyRate' : IDL.Nat,
  'pendingEarnings' : IDL.Nat,
  'partnerId' : IDL.Principal,
  'companyName' : IDL.Text,
  'rejectedTasks' : IDL.Nat,
  'pendingTasks' : IDL.Nat,
  'skills' : IDL.Vec(IDL.Text),
});

export const idlService = IDL.Service({
  '_initializeAccessControlWithSecret' : IDL.Func([IDL.Text], [], []),
  'acceptOffer' : IDL.Func([RequestId], [Request], []),
  'assignCallerUserRole' : IDL.Func([IDL.Principal, UserRole__1], [], []),
  'assignTaskToPartner' : IDL.Func(
      [RequestId, IDL.Principal, IDL.Text, IDL.Nat, IDL.Opt(Time)],
      [Request],
      [],
    ),
  'completeTask' : IDL.Func([RequestId, IDL.Text], [Request], []),
  'createRequest' : IDL.Func([RequestInput], [Request], []),
  'createSubscription' : IDL.Func(
      [
        IDL.Principal,
        BaseServiceType,
        IDL.Nat,
        IDL.Nat,
        Time,
        Time,
        ServiceStatus,
        IDL.Opt(IDL.Principal),
        IDL.Vec(IDL.Principal),
      ],
      [SubscriptionRecord],
      [],
    ),
  'getActiveSubscriptionsForCaller' : IDL.Func(
      [],
      [IDL.Vec(SubscriptionRecord)],
      [],
    ),
  'getAsistenmuRequests' : IDL.Func([], [IDL.Vec(Request)], ['query']),
  'getCallerUserProfile' : IDL.Func([], [IDL.Opt(UserProfile)], ['query']),
  'getCallerUserRole' : IDL.Func([], [UserRole__1], ['query']),
  'getClientRequests' : IDL.Func([], [IDL.Vec(Request)], ['query']),
  'getFilteredServices' : IDL.Func([ServiceFilter, IDL.Nat], [ServicePage], []),
  'getPartnerProfile' : IDL.Func(
      [IDL.Principal],
      [IDL.Opt(PartnerProfile)],
      ['query'],
    ),
  'getPartnerRequests' : IDL.Func([], [IDL.Vec(Request)], ['query']),
  'getRequest' : IDL.Func([RequestId], [IDL.Opt(Request)], ['query']),
  'getSubscriptionSummary' : IDL.Func([], [SubscriptionSummary], ['query']),
  'getUserIdentities' : IDL.Func(
      [IDL.Vec(IDL.Principal)],
      [IDL.Vec(UserIdentity)],
      ['query'],
    ),
  'getUserIdentity' : IDL.Func(
      [IDL.Principal],
      [IDL.Opt(UserIdentity)],
      ['query'],
    ),
  'getUserProfile' : IDL.Func(
      [IDL.Principal],
      [IDL.Opt(UserProfile)],
      ['query'],
    ),
  'initializeSystem' : IDL.Func([IDL.Text], [], []),
  'isCallerAdmin' : IDL.Func([], [IDL.Bool], ['query']),
  'registerAsistenmu' : IDL.Func([IDL.Principal, IDL.Text], [], []),
  'registerClient' : IDL.Func([IDL.Text], [], []),
  'registerPartner' : IDL.Func([IDL.Text, IDL.Text], [], []),
  'rejectOffer' : IDL.Func([RequestId, IDL.Text], [Request], []),
  'requestQA' : IDL.Func([RequestId], [Request], []),
  'requestRevision' : IDL.Func([RequestId, IDL.Text], [Request], []),
  'saveCallerUserProfile' : IDL.Func([UserProfile], [], []),
  'savePartnerProfile' : IDL.Func([PartnerProfile], [], []),
  'searchPartners' : IDL.Func(
      [PartnerSearchCriteria],
      [IDL.Vec(PartnerSearchResult)],
      ['query'],
    ),
  'updateSubscription' : IDL.Func(
      [
        IDL.Nat,
        IDL.Principal,
        BaseServiceType,
        IDL.Nat,
        IDL.Nat,
        Time,
        Time,
        ServiceStatus,
        IDL.Opt(IDL.Principal),
        IDL.Vec(IDL.Principal),
      ],
      [SubscriptionRecord],
      [],
    ),
});

export const idlInitArgs = [];

export const idlFactory = ({ IDL }) => {
  const RequestId = IDL.Nat;
  const Time = IDL.Int;
  const TaskStatus = IDL.Variant({
    'assignedAsPartner' : IDL.Record({
      'effectiveHours' : IDL.Nat,
      'partnerId' : IDL.Principal,
      'workDeadline' : IDL.Opt(Time),
      'workBriefing' : IDL.Text,
    }),
    'rejectedByPartner' : IDL.Record({ 'revisionByPartner' : IDL.Text }),
    'revisionRequestedByAsistenmu' : IDL.Record({
      'revisionByAsistenmu' : IDL.Text,
      'partnerId' : IDL.Principal,
    }),
    'newlyCreated' : IDL.Null,
    'qaRequestedByPartner' : IDL.Record({ 'partnerId' : IDL.Principal }),
    'offerSentToPartner' : IDL.Record({
      'effectiveHours' : IDL.Nat,
      'partnerId' : IDL.Principal,
      'workBriefing' : IDL.Text,
    }),
    'completedBYPartnerAndAsistenmu' : IDL.Record({
      'finalReport' : IDL.Text,
      'partnerId' : IDL.Principal,
    }),
    'inProgressByPartner' : IDL.Record({ 'partnerId' : IDL.Principal }),
  });
  const TaskRecordStatus = IDL.Variant({
    'active' : IDL.Null,
    'completed' : IDL.Null,
    'qaRequested' : IDL.Null,
    'rejected' : IDL.Null,
    'revisionRequested' : IDL.Null,
  });
  const Request = IDL.Record({
    'id' : RequestId,
    'status' : TaskStatus,
    'client' : IDL.Principal,
    'title' : IDL.Text,
    'createdAt' : Time,
    'revisionCount' : IDL.Nat,
    'deadline' : IDL.Opt(Time),
    'updatedAt' : Time,
    'details' : IDL.Text,
    'asistenmu' : IDL.Principal,
    'recordStatus' : TaskRecordStatus,
  });
  const UserRole__1 = IDL.Variant({
    'admin' : IDL.Null,
    'user' : IDL.Null,
    'guest' : IDL.Null,
  });
  const RequestInput = IDL.Record({
    'title' : IDL.Text,
    'deadline' : IDL.Opt(Time),
    'subscriptionId' : IDL.Nat,
    'details' : IDL.Text,
  });
  const BaseServiceType = IDL.Variant({
    'fokus' : IDL.Null,
    'jaga' : IDL.Null,
    'rapi' : IDL.Null,
    'tenang' : IDL.Null,
  });
  const ServiceStatus = IDL.Variant({
    'active' : IDL.Null,
    'hold' : IDL.Null,
    'suspended' : IDL.Null,
  });
  const SubscriptionRecord = IDL.Record({
    'id' : IDL.Nat,
    'status' : ServiceStatus,
    'client' : IDL.Principal,
    'serviceType' : BaseServiceType,
    'endDate' : Time,
    'pricePerService' : IDL.Nat,
    'quantity' : IDL.Nat,
    'asistenmu' : IDL.Opt(IDL.Principal),
    'sharedPrincipals' : IDL.Vec(IDL.Principal),
    'startDate' : Time,
  });
  const UserProfile = IDL.Record({
    'name' : IDL.Text,
    'whatsapp' : IDL.Text,
    'email' : IDL.Text,
    'company' : IDL.Opt(IDL.Text),
  });
  const ServiceFilter = IDL.Record({
    'status' : IDL.Opt(ServiceStatus),
    'serviceType' : IDL.Opt(BaseServiceType),
    'endDate' : IDL.Opt(Time),
    'minQuantity' : IDL.Opt(IDL.Nat),
    'startDate' : IDL.Opt(Time),
  });
  const ServicePage = IDL.Record({
    'subscriptions' : IDL.Vec(SubscriptionRecord),
    'total' : IDL.Nat,
    'page' : IDL.Nat,
    'pageSize' : IDL.Nat,
  });
  const PartnerProfile = IDL.Record({
    'completedTasks' : IDL.Nat,
    'hourlyRate' : IDL.Nat,
    'pendingEarnings' : IDL.Nat,
    'companyName' : IDL.Text,
    'rejectedTasks' : IDL.Nat,
    'pendingTasks' : IDL.Nat,
    'skills' : IDL.Vec(IDL.Text),
  });
  const SubscriptionSummary = IDL.Record({
    'totalSubscriptions' : IDL.Nat,
    'activeSubscriptions' : IDL.Nat,
    'hasActiveAsistenmu' : IDL.Bool,
  });
  const PartnerStatus = IDL.Variant({
    'active' : IDL.Null,
    'pending' : IDL.Null,
  });
  const UserRole = IDL.Variant({
    'client' : IDL.Null,
    'admin' : IDL.Null,
    'asistenmu' : IDL.Null,
    'partner' : PartnerStatus,
  });
  const UserIdentity = IDL.Record({
    'principal' : IDL.Principal,
    'name' : IDL.Text,
    'role' : UserRole,
  });
  const PartnerSearchCriteria = IDL.Record({
    'maxHourlyRate' : IDL.Opt(IDL.Nat),
    'minHourlyRate' : IDL.Opt(IDL.Nat),
    'companyName' : IDL.Opt(IDL.Text),
    'skills' : IDL.Opt(IDL.Text),
  });
  const PartnerSearchResult = IDL.Record({
    'completedTasks' : IDL.Nat,
    'hourlyRate' : IDL.Nat,
    'pendingEarnings' : IDL.Nat,
    'partnerId' : IDL.Principal,
    'companyName' : IDL.Text,
    'rejectedTasks' : IDL.Nat,
    'pendingTasks' : IDL.Nat,
    'skills' : IDL.Vec(IDL.Text),
  });
  
  return IDL.Service({
    '_initializeAccessControlWithSecret' : IDL.Func([IDL.Text], [], []),
    'acceptOffer' : IDL.Func([RequestId], [Request], []),
    'assignCallerUserRole' : IDL.Func([IDL.Principal, UserRole__1], [], []),
    'assignTaskToPartner' : IDL.Func(
        [RequestId, IDL.Principal, IDL.Text, IDL.Nat, IDL.Opt(Time)],
        [Request],
        [],
      ),
    'completeTask' : IDL.Func([RequestId, IDL.Text], [Request], []),
    'createRequest' : IDL.Func([RequestInput], [Request], []),
    'createSubscription' : IDL.Func(
        [
          IDL.Principal,
          BaseServiceType,
          IDL.Nat,
          IDL.Nat,
          Time,
          Time,
          ServiceStatus,
          IDL.Opt(IDL.Principal),
          IDL.Vec(IDL.Principal),
        ],
        [SubscriptionRecord],
        [],
      ),
    'getActiveSubscriptionsForCaller' : IDL.Func(
        [],
        [IDL.Vec(SubscriptionRecord)],
        [],
      ),
    'getAsistenmuRequests' : IDL.Func([], [IDL.Vec(Request)], ['query']),
    'getCallerUserProfile' : IDL.Func([], [IDL.Opt(UserProfile)], ['query']),
    'getCallerUserRole' : IDL.Func([], [UserRole__1], ['query']),
    'getClientRequests' : IDL.Func([], [IDL.Vec(Request)], ['query']),
    'getFilteredServices' : IDL.Func(
        [ServiceFilter, IDL.Nat],
        [ServicePage],
        [],
      ),
    'getPartnerProfile' : IDL.Func(
        [IDL.Principal],
        [IDL.Opt(PartnerProfile)],
        ['query'],
      ),
    'getPartnerRequests' : IDL.Func([], [IDL.Vec(Request)], ['query']),
    'getRequest' : IDL.Func([RequestId], [IDL.Opt(Request)], ['query']),
    'getSubscriptionSummary' : IDL.Func([], [SubscriptionSummary], ['query']),
    'getUserIdentities' : IDL.Func(
        [IDL.Vec(IDL.Principal)],
        [IDL.Vec(UserIdentity)],
        ['query'],
      ),
    'getUserIdentity' : IDL.Func(
        [IDL.Principal],
        [IDL.Opt(UserIdentity)],
        ['query'],
      ),
    'getUserProfile' : IDL.Func(
        [IDL.Principal],
        [IDL.Opt(UserProfile)],
        ['query'],
      ),
    'initializeSystem' : IDL.Func([IDL.Text], [], []),
    'isCallerAdmin' : IDL.Func([], [IDL.Bool], ['query']),
    'registerAsistenmu' : IDL.Func([IDL.Principal, IDL.Text], [], []),
    'registerClient' : IDL.Func([IDL.Text], [], []),
    'registerPartner' : IDL.Func([IDL.Text, IDL.Text], [], []),
    'rejectOffer' : IDL.Func([RequestId, IDL.Text], [Request], []),
    'requestQA' : IDL.Func([RequestId], [Request], []),
    'requestRevision' : IDL.Func([RequestId, IDL.Text], [Request], []),
    'saveCallerUserProfile' : IDL.Func([UserProfile], [], []),
    'savePartnerProfile' : IDL.Func([PartnerProfile], [], []),
    'searchPartners' : IDL.Func(
        [PartnerSearchCriteria],
        [IDL.Vec(PartnerSearchResult)],
        ['query'],
      ),
    'updateSubscription' : IDL.Func(
        [
          IDL.Nat,
          IDL.Principal,
          BaseServiceType,
          IDL.Nat,
          IDL.Nat,
          Time,
          Time,
          ServiceStatus,
          IDL.Opt(IDL.Principal),
          IDL.Vec(IDL.Principal),
        ],
        [SubscriptionRecord],
        [],
      ),
  });
};

export const init = ({ IDL }) => { return []; };