/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import type { ActorMethod } from '@icp-sdk/core/agent';
import type { IDL } from '@icp-sdk/core/candid';
import type { Principal } from '@icp-sdk/core/principal';

export type BaseServiceType = { 'fokus' : null } |
  { 'jaga' : null } |
  { 'rapi' : null } |
  { 'tenang' : null };
export interface PartnerProfile {
  'completedTasks' : bigint,
  'hourlyRate' : bigint,
  'pendingEarnings' : bigint,
  'companyName' : string,
  'rejectedTasks' : bigint,
  'pendingTasks' : bigint,
  'skills' : Array<string>,
}
export interface PartnerSearchCriteria {
  'maxHourlyRate' : [] | [bigint],
  'minHourlyRate' : [] | [bigint],
  'companyName' : [] | [string],
  'skills' : [] | [string],
}
export interface PartnerSearchResult {
  'completedTasks' : bigint,
  'hourlyRate' : bigint,
  'pendingEarnings' : bigint,
  'partnerId' : Principal,
  'companyName' : string,
  'rejectedTasks' : bigint,
  'pendingTasks' : bigint,
  'skills' : Array<string>,
}
export type PartnerStatus = { 'active' : null } |
  { 'pending' : null };
export interface Request {
  'id' : RequestId,
  'status' : TaskStatus,
  'client' : Principal,
  'title' : string,
  'createdAt' : Time,
  'revisionCount' : bigint,
  'deadline' : [] | [Time],
  'updatedAt' : Time,
  'details' : string,
  'asistenmu' : Principal,
  'recordStatus' : TaskRecordStatus,
}
export type RequestId = bigint;
export interface RequestInput {
  'title' : string,
  'deadline' : [] | [Time],
  'subscriptionId' : bigint,
  'details' : string,
}
export interface ServiceFilter {
  'status' : [] | [ServiceStatus],
  'serviceType' : [] | [BaseServiceType],
  'endDate' : [] | [Time],
  'minQuantity' : [] | [bigint],
  'startDate' : [] | [Time],
}
export interface ServicePage {
  'subscriptions' : Array<SubscriptionRecord>,
  'total' : bigint,
  'page' : bigint,
  'pageSize' : bigint,
}
export type ServiceStatus = { 'active' : null } |
  { 'hold' : null } |
  { 'suspended' : null };
export interface SubscriptionRecord {
  'id' : bigint,
  'status' : ServiceStatus,
  'client' : Principal,
  'serviceType' : BaseServiceType,
  'endDate' : Time,
  'pricePerService' : bigint,
  'quantity' : bigint,
  'asistenmu' : [] | [Principal],
  'sharedPrincipals' : Array<Principal>,
  'startDate' : Time,
}
export interface SubscriptionSummary {
  'totalSubscriptions' : bigint,
  'activeSubscriptions' : bigint,
  'hasActiveAsistenmu' : boolean,
}
export type TaskRecordStatus = { 'active' : null } |
  { 'completed' : null } |
  { 'qaRequested' : null } |
  { 'rejected' : null } |
  { 'revisionRequested' : null };
export type TaskStatus = {
    'assignedAsPartner' : {
      'effectiveHours' : bigint,
      'partnerId' : Principal,
      'workDeadline' : [] | [Time],
      'workBriefing' : string,
    }
  } |
  { 'rejectedByPartner' : { 'revisionByPartner' : string } } |
  {
    'revisionRequestedByAsistenmu' : {
      'revisionByAsistenmu' : string,
      'partnerId' : Principal,
    }
  } |
  { 'newlyCreated' : null } |
  { 'qaRequestedByPartner' : { 'partnerId' : Principal } } |
  {
    'offerSentToPartner' : {
      'effectiveHours' : bigint,
      'partnerId' : Principal,
      'workBriefing' : string,
    }
  } |
  {
    'completedBYPartnerAndAsistenmu' : {
      'finalReport' : string,
      'partnerId' : Principal,
    }
  } |
  { 'inProgressByPartner' : { 'partnerId' : Principal } };
export type Time = bigint;
export interface UserIdentity {
  'principal' : Principal,
  'name' : string,
  'role' : UserRole,
}
export interface UserProfile {
  'name' : string,
  'whatsapp' : string,
  'email' : string,
  'company' : [] | [string],
}
export type UserRole = { 'client' : null } |
  { 'admin' : null } |
  { 'asistenmu' : null } |
  { 'partner' : PartnerStatus };
export type UserRole__1 = { 'admin' : null } |
  { 'user' : null } |
  { 'guest' : null };
export interface _SERVICE {
  '_initializeAccessControlWithSecret' : ActorMethod<[string], undefined>,
  'acceptOffer' : ActorMethod<[RequestId], Request>,
  'assignCallerUserRole' : ActorMethod<[Principal, UserRole__1], undefined>,
  'assignTaskToPartner' : ActorMethod<
    [RequestId, Principal, string, bigint, [] | [Time]],
    Request
  >,
  'completeTask' : ActorMethod<[RequestId, string], Request>,
  'createRequest' : ActorMethod<[RequestInput], Request>,
  'createSubscription' : ActorMethod<
    [
      Principal,
      BaseServiceType,
      bigint,
      bigint,
      Time,
      Time,
      ServiceStatus,
      [] | [Principal],
      Array<Principal>,
    ],
    SubscriptionRecord
  >,
  'getActiveSubscriptionsForCaller' : ActorMethod<
    [],
    Array<SubscriptionRecord>
  >,
  'getAsistenmuRequests' : ActorMethod<[], Array<Request>>,
  'getCallerUserProfile' : ActorMethod<[], [] | [UserProfile]>,
  'getCallerUserRole' : ActorMethod<[], UserRole__1>,
  'getClientRequests' : ActorMethod<[], Array<Request>>,
  'getFilteredServices' : ActorMethod<[ServiceFilter, bigint], ServicePage>,
  'getPartnerProfile' : ActorMethod<[Principal], [] | [PartnerProfile]>,
  'getPartnerRequests' : ActorMethod<[], Array<Request>>,
  'getRequest' : ActorMethod<[RequestId], [] | [Request]>,
  'getSubscriptionSummary' : ActorMethod<[], SubscriptionSummary>,
  'getUserIdentities' : ActorMethod<[Array<Principal>], Array<UserIdentity>>,
  'getUserIdentity' : ActorMethod<[Principal], [] | [UserIdentity]>,
  'getUserProfile' : ActorMethod<[Principal], [] | [UserProfile]>,
  'initializeSystem' : ActorMethod<[string], undefined>,
  'isCallerAdmin' : ActorMethod<[], boolean>,
  'registerAsistenmu' : ActorMethod<[Principal, string], undefined>,
  'registerClient' : ActorMethod<[string], undefined>,
  'registerPartner' : ActorMethod<[string, string], undefined>,
  'rejectOffer' : ActorMethod<[RequestId, string], Request>,
  'requestQA' : ActorMethod<[RequestId], Request>,
  'requestRevision' : ActorMethod<[RequestId, string], Request>,
  'saveCallerUserProfile' : ActorMethod<[UserProfile], undefined>,
  'savePartnerProfile' : ActorMethod<[PartnerProfile], undefined>,
  'searchPartners' : ActorMethod<
    [PartnerSearchCriteria],
    Array<PartnerSearchResult>
  >,
  'updateSubscription' : ActorMethod<
    [
      bigint,
      Principal,
      BaseServiceType,
      bigint,
      bigint,
      Time,
      Time,
      ServiceStatus,
      [] | [Principal],
      Array<Principal>,
    ],
    SubscriptionRecord
  >,
}
export declare const idlService: IDL.ServiceClass;
export declare const idlInitArgs: IDL.Type[];
export declare const idlFactory: IDL.InterfaceFactory;
export declare const init: (args: { IDL: typeof IDL }) => IDL.Type[];